# ---------------------------------------------------------------------------
# The Kanardia fonts, generated at build time
#
# Kanardia.ttf is the product font: Roboto with Kanardia's own unit glyphs
# merged in, and those live in the private-use area from 0xE000. It is turned
# into C by lv_font_conv -- LVGL's own font pipeline, the same tool
# scripts/built_in_font/ uses to generate the Montserrat fonts -- so no
# generated font source is ever checked in and a size change is a one-line edit
# in KANARDIA_FONT_SIZES.
#
# Both builds generate the same fonts from the same TTF, which is why this is a
# function rather than a copy in each CMakeLists.txt: a font that differed
# between the panel and the simulator would make every screenshot comparison a
# lie.
#
#     kanardia_add_fonts(<target>)
#
# generates one .c per size plus a KanardiaFont.h holding the LV_FONT_DECLAREs
# and the KANARDIA_FONT_LIST(X) X-macro that Painter::CreateFont() builds its
# lookup table from, adds them to <target>, and puts the generated header on
# its include path.
#
# lv_font_conv is a Node tool and is part of neither ESP-IDF nor a desktop
# toolchain. Install it once:
#
#     npm install --prefix tools lv_font_conv
#
# or globally, or point -DLV_FONT_CONV=/path/to/lv_font_conv at an existing one.
# ---------------------------------------------------------------------------

# The repository root, whoever included us.
if(NOT DEFINED KANARDIA_ROOT)
    get_filename_component(KANARDIA_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

set(KANARDIA_FONT_TTF "${KANARDIA_BRANCH}/Public/Nesis/support/Kanardia.ttf"
    CACHE FILEPATH "TTF the LVGL fonts are generated from")

set(KANARDIA_FONT_SIZES "14;16;20;28"
    CACHE STRING "Pixel sizes to generate, smallest first")

# ASCII, degree sign, bullet -- LVGL's own default range -- plus the unit
# glyphs. The font carries 0xE000..0xE118 in the private-use area; anything in
# the range with no glyph behind it is simply skipped by lv_font_conv.
set(KANARDIA_FONT_RANGES "0x20-0x7F,0xB0,0x2022,0xE000-0xE118"
    CACHE STRING "Codepoints to include")

set(KANARDIA_FONT_BPP "4"
    CACHE STRING "Anti-aliasing depth; 4 is what LVGL's built-in fonts use")

function(kanardia_add_fonts TARGET)
    find_program(LV_FONT_CONV
        NAMES lv_font_conv
        HINTS "${KANARDIA_ROOT}/tools/node_modules/.bin"
        DOC "LVGL font converter (npm install --prefix tools lv_font_conv)")

    if(NOT LV_FONT_CONV)
        message(FATAL_ERROR
            "lv_font_conv not found -- the Kanardia fonts are generated at build "
            "time and cannot be built without it.\n"
            "  npm install --prefix ${KANARDIA_ROOT}/tools lv_font_conv\n"
            "or pass -DLV_FONT_CONV=/path/to/lv_font_conv.")
    endif()

    if(NOT EXISTS "${KANARDIA_FONT_TTF}")
        message(FATAL_ERROR "Font not found: ${KANARDIA_FONT_TTF}")
    endif()

    set(FONT_OUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/fonts")
    file(MAKE_DIRECTORY "${FONT_OUT_DIR}")

    set(FONT_SRCS "")
    set(FONT_DECLS "")
    set(FONT_XLIST "")

    foreach(size IN LISTS KANARDIA_FONT_SIZES)
        # lv_font_conv derives both the C symbol and its include guard from the
        # output file name, so the file name is the font name.
        set(font_name "lv_font_kanardia_${size}")
        set(font_src  "${FONT_OUT_DIR}/${font_name}.c")

        add_custom_command(
            OUTPUT "${font_src}"
            COMMAND "${LV_FONT_CONV}"
                    --font "${KANARDIA_FONT_TTF}"
                    -r "${KANARDIA_FONT_RANGES}"
                    --size ${size}
                    --bpp ${KANARDIA_FONT_BPP}
                    --no-compress --no-prefilter
                    --force-fast-kern-format
                    --format lvgl
                    -o "${font_src}"
            DEPENDS "${KANARDIA_FONT_TTF}"
            COMMENT "lv_font_conv: Kanardia ${size} px"
            VERBATIM)

        list(APPEND FONT_SRCS "${font_src}")
        string(APPEND FONT_DECLS "LV_FONT_DECLARE(${font_name})\n")
        string(APPEND FONT_XLIST "    X(${size}, ${font_name}) \\\n")
    endforeach()

    # The header is generated alongside the fonts so the two can never drift:
    # edit KANARDIA_FONT_SIZES and the declarations follow.
    #
    # It is written once at configure time and then *copied* into place by a
    # build rule, rather than written straight to its final path. Ninja can only
    # rebuild what it has a rule for, and without the copy step a deleted header
    # stays deleted until the next reconfigure.
    set(FONT_HEADER_IN  "${CMAKE_CURRENT_BINARY_DIR}/font_template/KanardiaFont.h")
    set(FONT_HEADER_OUT "${FONT_OUT_DIR}/KanardiaFont.h")

    file(WRITE "${FONT_HEADER_IN}" "#pragma once

// Generated by cmake/KanardiaFonts.cmake from ${KANARDIA_FONT_TTF}
// -- do not edit.
// Ranges: ${KANARDIA_FONT_RANGES}

#include \"lvgl.h\"

${FONT_DECLS}
// Every generated size, smallest first: X(px, symbol).
#define KANARDIA_FONT_LIST(X) \\
${FONT_XLIST}
")

    add_custom_command(
        OUTPUT "${FONT_HEADER_OUT}"
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${FONT_HEADER_IN}" "${FONT_HEADER_OUT}"
        DEPENDS "${FONT_HEADER_IN}"
        COMMENT "Generating KanardiaFont.h"
        VERBATIM)

    add_custom_target(kanardia_fonts DEPENDS ${FONT_SRCS} "${FONT_HEADER_OUT}")

    # The generated sources say #include "lvgl/lvgl.h" unless told otherwise,
    # and both builds put the header at plain "lvgl.h".
    # DIRECTORY is the caller's, not this file's: inside a function
    # CMAKE_CURRENT_LIST_DIR still points at cmake/, and the property has to
    # land in the directory scope the sources are compiled in.
    set_source_files_properties(${FONT_SRCS}
        DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        PROPERTIES GENERATED TRUE COMPILE_DEFINITIONS "LV_LVGL_H_INCLUDE_SIMPLE")

    target_sources(${TARGET} PRIVATE ${FONT_SRCS})
    target_include_directories(${TARGET} PUBLIC "${FONT_OUT_DIR}")
    add_dependencies(${TARGET} kanardia_fonts)
endfunction()
